kind: pipeline
type: docker
name: linux-arm

platform:
  arch: arm
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: Dockerfile
    build_args:
      - BUILD_ALL_CLIS="false"

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    dockerfile: Dockerfile
    build_args:
      - BUILD_ALL_CLIS="false"


