# Container image name consists of QUAY_USERNAME and workflow name.
name: 'argocd'

on:
  push:
    branches:
      - master

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          CONTAINER_IMAGE=quay.io/${{ secrets.QUAY_USERNAME }}/${GITHUB_WORKFLOW}
          VERSIONREF="$(cat ./VERSION)-${GITHUB_SHA::8}"
          SHORTREF="${GITHUB_SHA::8}"
          TAGS="${CONTAINER_IMAGE}:latest,${CONTAINER_IMAGE}:${VERSIONREF},${CONTAINER_IMAGE}:${SHORTREF}"

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${CONTAINER_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          # platforms: amd64
          platforms: amd64,arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
